### ISSUE TITLE
tensorflow>=1.8.0 now installs 2.0 alpha which breaks some things

### ISSUE THREAD

**Issue by cottrell** [openai/spinningup#155]
I would suggest either specifying an exact version or just converting the code to 2.0.

I'm not sure when this tensorflow pip resolving thing changed.

```
$ python -m spinup.run ppo --hid "[32,32]" --env LunarLander-v2 --exp_name installtest --gamma 0.999
Traceback (most recent call last):
  File "/home/cottrell/anaconda3/envs/spinningup/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/cottrell/anaconda3/envs/spinningup/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/cottrell/dev/spinningup/spinup/__init__.py", line 3, in <module>
    from spinup.algos.ppo.ppo import ppo
  File "/home/cottrell/dev/spinningup/spinup/algos/ppo/ppo.py", line 7, in <module>
    from spinup.utils.mpi_tf import MpiAdamOptimizer, sync_all_params
  File "/home/cottrell/dev/spinningup/spinup/utils/mpi_tf.py", line 29, in <module>
    class MpiAdamOptimizer(tf.train.AdamOptimizer):
AttributeError: module 'tensorflow._api.v2.train' has no attribute 'AdamOptimizer'
```

**Comment by jachiam** [comment]
Should be fixed by @bchess PR for version pin. Thanks!
