### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by thesupermanreturns** [openai/spinningup#26]
python -m spinup.run test_policy data/installtest/installtest_s0
Traceback (most recent call last):
  File "/Users/pritee/anaconda3/envs/spinningup/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/pritee/anaconda3/envs/spinningup/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/pritee/anaconda3/envs/spinningup/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/pritee/anaconda3/envs/spinningup/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/pritee/anaconda3/envs/spinningup/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/pritee/anaconda3/envs/spinningup/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _clock_gettime
  Referenced from: /Users/pritee/anaconda3/envs/spinningup/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/pritee/anaconda3/envs/spinningup/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pritee/anaconda3/envs/spinningup/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/pritee/anaconda3/envs/spinningup/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/pritee/spinningup/spinup/__init__.py", line 2, in <module>
    from spinup.algos.ddpg.ddpg import ddpg
  File "/Users/pritee/spinningup/spinup/algos/ddpg/ddpg.py", line 2, in <module>
    import tensorflow as tf
  File "/Users/pritee/anaconda3/envs/spinningup/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/Users/pritee/anaconda3/envs/spinningup/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/pritee/anaconda3/envs/spinningup/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/pritee/anaconda3/envs/spinningup/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/pritee/anaconda3/envs/spinningup/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/pritee/anaconda3/envs/spinningup/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/pritee/anaconda3/envs/spinningup/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/pritee/anaconda3/envs/spinningup/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/pritee/anaconda3/envs/spinningup/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _clock_gettime
  Referenced from: /Users/pritee/anaconda3/envs/spinningup/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/pritee/anaconda3/envs/spinningup/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by jachiam** [comment]
It's hard to say what's going on here without some more information, but it looks like your tensorflow installation is the issue.

What system and Python environment are you using? How was Tensorflow installed?

**Comment by kumarankit0411** [comment]
@thesupermanreturns Tensorflow version seems to be the problem. Make sure you are using latest tensorflow version possibly 1.10 or later.
