### ISSUE TITLE
Spinning up on Windows 10, successfully installed but can't run the test

### ISSUE THREAD

**Issue by Clorky** [openai/spinningup#290]
Hey guys,

so I've managed to make it work following this post #215 .

The environment seems fine as no errors occur when doing the `pip install e .` command. I'm running Python 3.6.10 in both base and spinningup environment as there was supposedly an issue with the run_entrypoint.py running a different version of Python than the version of the environment it is in.

I've tried googling and going through issues here, but couldn't find a solution apart from one that's for Linux.

There's this issue now, when I try to run the test:

`python -m spinup.run ppo --hid "[32,32]" --env LunarLander-v2 --exp_name installtest --gamma 0.999`

This error occurs:

> Using default backend (pytorch) for ppo.
> 
> ================================================================================
> ExperimentGrid [installtest] runs over parameters:
> 
>  gamma                                    [gam]
> 
>         0.999
> 
>  env_name                                 [env]
> 
>         LunarLander-v2
> 
>  ac_kwargs:hidden_sizes                   [ac-hid]
> 
>         [32, 32]
> 
>  Variants, counting seeds:               1
>  Variants, not counting seeds:           1
> 
> ================================================================================
> 
> Preparing to run the following experiments...
> 
> installtest
> 
> ================================================================================
> 
> Launch delayed to give you a few seconds to review your experiments.
> 
> To customize or disable this behavior, change WAIT_BEFORE_LAUNCH in
> spinup/user_config.py.
> 
> ================================================================================
> Running experiment:
> 
> installtest
> 
> with kwargs:
> 
> {
>     "ac_kwargs":        {
>         "hidden_sizes": [
>             32,
>             32
>         ]
>     },
>     "env_name": "LunarLander-v2",
>     "gamma":    0.999,
>     "seed":     0
> }
> 
> 
> Traceback (most recent call last):
>   File "c:\spinningup\spinup\utils\run_entrypoint.py", line 10, in <module>
>     thunk = pickle.loads(zlib.decompress(base64.b64decode(args.encoded_thunk)))
> ModuleNotFoundError: No module named 'spinup'
> 
> 
> 
> ================================================================================
> 
> 
> There appears to have been an error in your experiment.
> 
> Check the traceback above to see what actually went wrong. The
> traceback below, included for completeness (but probably not useful
> for diagnosing the error), shows the stack leading up to the
> experiment launch.
> 
> ================================================================================
> 
> 
> 
> Traceback (most recent call last):
>   File "E:\Anaconda\envs\spinningup\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "E:\Anaconda\envs\spinningup\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "c:\spinningup\spinup\run.py", line 248, in <module>
>     parse_and_execute_grid_search(cmd, args)
>   File "c:\spinningup\spinup\run.py", line 180, in parse_and_execute_grid_search
>     eg.run(algo, **run_kwargs)
>   File "c:\spinningup\spinup\utils\run_utils.py", line 546, in run
>     data_dir=data_dir, datestamp=datestamp, **var)
>   File "c:\spinningup\spinup\utils\run_utils.py", line 171, in call_experiment
>     subprocess.check_call(cmd, env=os.environ)
>   File "E:\Anaconda\envs\spinningup\lib\subprocess.py", line 311, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['E:\\Anaconda\\envs\\spinningup\\python.exe', 'c:\\spinningup\\spinup\\utils\\run_entrypoint.py', 'eJyNU0Fv0zAUdpqu69ptTEzaxLTDJA50QkQTEhc0xqESHDLtMDgOWW7sJiGJHWJ7Y0hISGNrJ1lcZrjwn7jzKzhy4MJzOtbCiVhJnt/z+/y+z88fmp9/+ah+zHqUC03LNMpyFszY1izjYZrneKh5pFLB7ZXtJcjcwgXJGJYZm4TADd4lPNBprlKO1WnJwGfafUHZSzc5t4e2F6J6+OFq/xn1xo2sVe3QBkU5uoQZ9e6gSzRCI2/YoD5tfmyDb24XucgTpLyxf+Z5aNwcgucTWBS9QLZ3YNqMH2NOCmZDlCz82aQBm3TG3ms0RmceLDw4t6bpqoZSts296PGRLFPOUx7rsjbhp1Way6NKc1xbQXkKFHZzUgwo2bPh1z6ySdf48WlhL+y2AkrmUURAHva2ZFVaMK6C3VyAS+4FKtE8w2Wu5dR3g2Varught8omq6ZdlCkeiipzsMmK6Uxzbfilv4wabc+N217Lb/uQnJ2QKpbWzHNd4KjU1szVKXYEBSarF9bVFvrvbc90MS5JlJGYYWzN4oRpUPMDcrgWzkXWZiPBjQb1GmgBtyZZ0SPAdajzcS4GQAkmycY/uY6MEgKCycaVlaZN2ZDoXEl7YJo0jRQkmWXoMqkrho9Jrpm0r2zP4c7FpCiIff70x89v39dG90Hu5X3NSbVPOGXVg+OH1iyQCF8LAECLSUop41im7yYw4Va4xaRpSsYodIRZykUcs2qa0jMdoVWpFaZpZc2Dv1uBEkWOUi4VnKtiUs3aWO6AHnDYk3Yz3ZmY1Tr0zOa1EiSPhesfJaooCcpSuNca332vLDOtQlAN9yvZNs0aK9k0PhURSLSOZy4glnowWeq4mS7hXCjibmJNvv1Gk3xSy93/aERrOtnJ9DS0Ogx+A0pugLU=']' returned non-zero exit status 1.

**Comment by Clorky** [comment]
I somehow managed to fix this.

One of these ideas helped:

1. I had some python installation that popped up after using the 'where python' command in `C:\Users\Petr\AppData\Local\Microsoft\WindowsApps`

No clue why. Deleted it.

2. I deleted the cloned repository from this step in the installation guide `git clone https://github.com/openai/spinningup.git` and I cloned it into a new folder.
