### ISSUE TITLE
Custom_Environment is not registered with Gym

### ISSUE THREAD

**Issue by Maldades** [openai/spinningup#317]
Hello,

I have created a docker container with SpinningUp and all its dependencies installed.
I have also created a gym environment following: https://github.com/openai/gym/blob/master/docs/creating-environments.md, and installed it with pip install -e .

If I run python -m spinup.run ppo --env MyEnv-v0, I get: 
```

Using default backend (pytorch) for ppo.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/spinningup/spinup/run.py", line 248, in <module>
    parse_and_execute_grid_search(cmd, args)
  File "/spinningup/spinup/run.py", line 173, in parse_and_execute_grid_search
    assert env_name in valid_envs, err_msg
AssertionError: 

Tersq-v0 is not registered with Gym.

Recommendations:

    * Check for a typo (did you include the version tag?)

    * View the complete list of valid Gym environments at

        https://gym.openai.com/envs/
```

However, it works if I execute a python script which imports gym, makes my env and so on.

Any clues on why spinningup might not find my environment among the registered ones?
Thank you!

**Comment by Maldades** [comment]
Hi! I found the solution for now, in case anyone else is struggling with this.
Just don't rely on calling spinup from the command line.
Try calling it from script, just a few paragraphs below in the tutorial.

Whatever, this has driven me nuts for two weeks ( n_nU )
Closing the issue.
