### ISSUE TITLE
Error when spinup.run plot for installtest on MacOS Bug Sur

### ISSUE THREAD

**Issue by shwnyao** [openai/spinningup#332]
My anaconda setup was following the tutorial, using python 3.6

running first line was successful.
`python -m spinup.run ppo --hid "[32,32]" --env LunarLander-v2 --exp_name installtest --gamma 0.999` 

sencond line has some issue but `pip install pyglet==1.5.11` soved it.
`python -m spinup.run test_policy data/installtest/installtest_s0`

third line and I'm facing this
```
python -m spinup.run plot data/installtest/installtest_s0
Plotting from...
==================================================

data/installtest/installtest_s0

==================================================
/Users/sangwen/opt/anaconda3/envs/spinningup/lib/python3.6/site-packages/seaborn/timeseries.py:183: UserWarning: The tsplot function is deprecated and will be removed or replaced (in a substantially altered version) in a future release.
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "/Users/sangwen/opt/anaconda3/envs/spinningup/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/sangwen/opt/anaconda3/envs/spinningup/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/sangwen/Projects/openai/spinningup/spinup/run.py", line 243, in <module>
    subprocess.check_call(args, env=os.environ)
  File "/Users/sangwen/opt/anaconda3/envs/spinningup/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/sangwen/opt/anaconda3/envs/spinningup/bin/python3', '/Users/sangwen/Projects/openai/spinningup/spinup/utils/plot.py', 'data/installtest/installtest_s0']' died with <Signals.SIGSEGV: 11>.
```

**Comment by mpiseno** [comment]
I am also facing this issue. Tried on both python 3.6 and 3.7.

EDIT: Looks like the issue is coming from the plt.plot() call in the make_plots function in spinup/utils/plot.py. This seems related to [this](https://github.com/matplotlib/matplotlib/issues/18953) issue with Matplotlib version 3.1.1 on MacOs Big Sur. Upgrading Matplotlib via:

`pip install matplotlib==3.3.3`

fixed this for me.

**Comment by MichaelrMentele** [comment]
Thanks for the share @mpiseno  !

Note: seems to work but creates a dep conflict.

**Comment by jramirezpr** [comment]
we get to see the plot, but get error msg:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spinup 0.2.0 requires matplotlib==3.1.1, but you have matplotlib 3.3.3 which is incompatible.

**Comment by zarifaziz** [comment]
how can this be fixed in the dependency tree of the project?

Edit: nevermind I just saw there are many PRs in this repo which are never getting merged. So no point.

**Comment by etekmen13** [comment]
Still facing this issue using in-box WSL2 running the Ubuntu 2204.3.63.0 installed as an application package. I am following the spinningup installation tutorial.

**Edit:**  solved by updating gcc `conda install -c conda-forge gcc=12.1.0`

Im running this line:
` xvfb-run python -m spinup.run test_policy data/installtest/installtest_s0`

and getting this:
```
xvfb-run python -m spinup.run test_policy data/installtest/installtest_s0

Loading from data/installtest/installtest_s0/pyt_save/model.pt.

/home/emre/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Logging data to /tmp/experiments/1722369849/progress.txt
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
Traceback (most recent call last):
  File "/home/emre/spinningup/spinup/utils/test_policy.py", line 153, in <module>
    run_policy(env, get_action, args.len, args.episodes, not(args.norender))
    env.render()
  File "/home/emre/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/core.py", line 235, in render
    return self.env.render(mode, **kwargs)
  File "/home/emre/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/envs/box2d/lunar_lander.py", line 320, in render
    from gym.envs.classic_control import rendering
  File "/home/emre/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 27, in <module>
    from pyglet.gl import *
  File "/home/emre/anaconda3/envs/spinningup/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 244, in <module>
    import pyglet.window
  File "/home/emre/anaconda3/envs/spinningup/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1880, in <module>
    gl._create_shadow_window()
  File "/home/emre/anaconda3/envs/spinningup/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 220, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/emre/anaconda3/envs/spinningup/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 165, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/emre/anaconda3/envs/spinningup/lib/python3.6/site-packages/pyglet/window/__init__.py", line 591, in __init__
    context = config.create_context(gl.current_context)
  File "/home/emre/anaconda3/envs/spinningup/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 204, in create_context
    return XlibContextARB(self, share)
  File "/home/emre/anaconda3/envs/spinningup/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 314, in __init__
    super(XlibContext13, self).__init__(config, share)
  File "/home/emre/anaconda3/envs/spinningup/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 218, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context
Traceback (most recent call last):
  File "/home/emre/anaconda3/envs/spinningup/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/emre/anaconda3/envs/spinningup/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/emre/spinningup/spinup/run.py", line 243, in <module>
    subprocess.check_call(args, env=os.environ)
  File "/home/emre/anaconda3/envs/spinningup/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/emre/anaconda3/envs/spinningup/bin/python', '/home/emre/spinningup/spinup/utils/test_policy.py', 'data/installtest/installtest_s0']' returned non-zero exit status 1.```
