### ISSUE TITLE
Getting an error when installing the corresponding Gym environments

### ISSUE THREAD

**Issue by HasarinduPerera** [openai/spinningup#352]
After installing Mujoco 2.1.0 (new open source package), I have set the **.bashrc** to 
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/user/.mujoco/mujoco210/bin`  
(When I install mujoco-py it requested to set the path as this) but now the error message says:
`You appear to be missing MuJoCo.  We expected to find the file here: /home/user/.mujoco/mjpro150`

`pip install gym[mujoco,robotics]`

```
Requirement already satisfied: gym[mujoco,robotics] in /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages (0.15.7)
Requirement already satisfied: scipy in /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages (from gym[mujoco,robotics]) (1.5.4)
Requirement already satisfied: numpy>=1.10.4 in /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages (from gym[mujoco,robotics]) (1.18.5)
Requirement already satisfied: six in /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages (from gym[mujoco,robotics]) (1.16.0)
Requirement already satisfied: cloudpickle~=1.2.0 in /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages (from gym[mujoco,robotics]) (1.2.1)
Requirement already satisfied: pyglet<=1.5.0,>=1.4.0 in /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages (from gym[mujoco,robotics]) (1.5.0)
Collecting mujoco-py<2.0,>=1.50
  Using cached mujoco-py-1.50.1.68.tar.gz (120 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: imageio in /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages (from gym[mujoco,robotics]) (2.10.4)
Requirement already satisfied: glfw>=1.4.0 in /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages (from mujoco-py<2.0,>=1.50->gym[mujoco,robotics]) (2.4.0)
Requirement already satisfied: Cython>=0.27.2 in /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages (from mujoco-py<2.0,>=1.50->gym[mujoco,robotics]) (0.29.24)
Requirement already satisfied: cffi>=1.10 in /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages (from mujoco-py<2.0,>=1.50->gym[mujoco,robotics]) (1.15.0)
Requirement already satisfied: lockfile>=0.12.2 in /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages (from mujoco-py<2.0,>=1.50->gym[mujoco,robotics]) (0.12.2)
Requirement already satisfied: pillow>=8.3.2 in /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages (from imageio->gym[mujoco,robotics]) (8.4.0)
Requirement already satisfied: future in /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages (from pyglet<=1.5.0,>=1.4.0->gym[mujoco,robotics]) (0.18.2)
Requirement already satisfied: pycparser in /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages (from cffi>=1.10->mujoco-py<2.0,>=1.50->gym[mujoco,robotics]) (2.21)
Building wheels for collected packages: mujoco-py
  Building wheel for mujoco-py (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/user/anaconda3/envs/spinningup/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jvze_h7i/mujoco-py_35a193b81cbb4e02a16072099553e4b4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jvze_h7i/mujoco-py_35a193b81cbb4e02a16072099553e4b4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-4jr5y9f8
       cwd: /tmp/pip-install-jvze_h7i/mujoco-py_35a193b81cbb4e02a16072099553e4b4/
  Complete output (54 lines):
  running bdist_wheel
  running build
  
  You appear to be missing MuJoCo.  We expected to find the file here: /home/user/.mujoco/mjpro150
  
  This package only provides python bindings, the library must be installed separately.
  
  Please follow the instructions on the README to install MuJoCo
  
      https://github.com/openai/mujoco-py#install-mujoco
  
  Which can be downloaded from the website
  
      https://www.roboti.us/index.html
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-jvze_h7i/mujoco-py_35a193b81cbb4e02a16072099553e4b4/setup.py", line 44, in <module>
      tests_require=read_requirements_file('requirements.dev.txt'),
    File "/home/user/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/home/user/anaconda3/envs/spinningup/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/user/anaconda3/envs/spinningup/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/user/anaconda3/envs/spinningup/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/user/anaconda3/envs/spinningup/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/user/anaconda3/envs/spinningup/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-jvze_h7i/mujoco-py_35a193b81cbb4e02a16072099553e4b4/setup.py", line 28, in run
      import mujoco_py  # noqa: force build
    File "/tmp/pip-install-jvze_h7i/mujoco-py_35a193b81cbb4e02a16072099553e4b4/mujoco_py/__init__.py", line 3, in <module>
      from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
    File "/tmp/pip-install-jvze_h7i/mujoco-py_35a193b81cbb4e02a16072099553e4b4/mujoco_py/builder.py", line 502, in <module>
      mjpro_path, key_path = discover_mujoco()
    File "/tmp/pip-install-jvze_h7i/mujoco-py_35a193b81cbb4e02a16072099553e4b4/mujoco_py/utils.py", line 93, in discover_mujoco
      raise Exception(message)
  Exception:
  You appear to be missing MuJoCo.  We expected to find the file here: /home/user/.mujoco/mjpro150
  
  This package only provides python bindings, the library must be installed separately.
  
  Please follow the instructions on the README to install MuJoCo
  
      https://github.com/openai/mujoco-py#install-mujoco
  
  Which can be downloaded from the website
  
      https://www.roboti.us/index.html
  
  ----------------------------------------
  ERROR: Failed building wheel for mujoco-py
  Running setup.py clean for mujoco-py
Failed to build mujoco-py
Installing collected packages: mujoco-py
  Attempting uninstall: mujoco-py
    Found existing installation: mujoco-py 2.0.2.13
    Uninstalling mujoco-py-2.0.2.13:
      Successfully uninstalled mujoco-py-2.0.2.13
    Running setup.py install for mujoco-py ... error
    ERROR: Command errored out with exit status 1:
     command: /home/user/anaconda3/envs/spinningup/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jvze_h7i/mujoco-py_35a193b81cbb4e02a16072099553e4b4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jvze_h7i/mujoco-py_35a193b81cbb4e02a16072099553e4b4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7uj0wk9y/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/anaconda3/envs/spinningup/include/python3.6m/mujoco-py
         cwd: /tmp/pip-install-jvze_h7i/mujoco-py_35a193b81cbb4e02a16072099553e4b4/
    Complete output (56 lines):
    running install
    running build
    
    You appear to be missing MuJoCo.  We expected to find the file here: /home/user/.mujoco/mjpro150
    
    This package only provides python bindings, the library must be installed separately.
    
    Please follow the instructions on the README to install MuJoCo
    
        https://github.com/openai/mujoco-py#install-mujoco
    
    Which can be downloaded from the website
    
        https://www.roboti.us/index.html
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jvze_h7i/mujoco-py_35a193b81cbb4e02a16072099553e4b4/setup.py", line 44, in <module>
        tests_require=read_requirements_file('requirements.dev.txt'),
      File "/home/user/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/home/user/anaconda3/envs/spinningup/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/user/anaconda3/envs/spinningup/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/user/anaconda3/envs/spinningup/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/user/.local/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/user/anaconda3/envs/spinningup/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/user/anaconda3/envs/spinningup/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/user/anaconda3/envs/spinningup/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-jvze_h7i/mujoco-py_35a193b81cbb4e02a16072099553e4b4/setup.py", line 28, in run
        import mujoco_py  # noqa: force build
      File "/tmp/pip-install-jvze_h7i/mujoco-py_35a193b81cbb4e02a16072099553e4b4/mujoco_py/__init__.py", line 3, in <module>
        from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
      File "/tmp/pip-install-jvze_h7i/mujoco-py_35a193b81cbb4e02a16072099553e4b4/mujoco_py/builder.py", line 502, in <module>
        mjpro_path, key_path = discover_mujoco()
      File "/tmp/pip-install-jvze_h7i/mujoco-py_35a193b81cbb4e02a16072099553e4b4/mujoco_py/utils.py", line 93, in discover_mujoco
        raise Exception(message)
    Exception:
    You appear to be missing MuJoCo.  We expected to find the file here: /home/user/.mujoco/mjpro150
    
    This package only provides python bindings, the library must be installed separately.
    
    Please follow the instructions on the README to install MuJoCo
    
        https://github.com/openai/mujoco-py#install-mujoco
    
    Which can be downloaded from the website
    
        https://www.roboti.us/index.html
    
    ----------------------------------------
  Rolling back uninstall of mujoco-py
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py-2.0.2.13.dist-info/
   from /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/~ujoco_py-2.0.2.13.dist-info
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/__init__.py
   from /tmp/pip-uninstall-rdeaw6f9/__init__.py
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/__pycache__/
   from /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/~_pycache__
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/builder.py
   from /tmp/pip-uninstall-rdeaw6f9/builder.py
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/cymj.c
   from /tmp/pip-uninstall-rdeaw6f9/cymj.c
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/cymj.pyx
   from /tmp/pip-uninstall-rdeaw6f9/cymj.pyx
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/generated/__init__.py
   from /tmp/pip-uninstall-rdeaw6f9/generated/__init__.py
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/generated/__pycache__/
   from /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/generated/~_pycache__
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/generated/const.py
   from /tmp/pip-uninstall-rdeaw6f9/generated/const.py
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/generated/cymj_2.0.2.13_36_linuxgpuextensionbuilder_36.so
   from /tmp/pip-uninstall-rdeaw6f9/generated/cymj_2.0.2.13_36_linuxgpuextensionbuilder_36.so
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/generated/wrappers.pxi
   from /tmp/pip-uninstall-rdeaw6f9/generated/wrappers.pxi
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/gl/
   from /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/~l
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/mjbatchrenderer.pyx
   from /tmp/pip-uninstall-rdeaw6f9/mjbatchrenderer.pyx
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/mjpid.pyx
   from /tmp/pip-uninstall-rdeaw6f9/mjpid.pyx
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/mjrendercontext.pyx
   from /tmp/pip-uninstall-rdeaw6f9/mjrendercontext.pyx
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/mjrenderpool.py
   from /tmp/pip-uninstall-rdeaw6f9/mjrenderpool.py
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/mjsim.pyx
   from /tmp/pip-uninstall-rdeaw6f9/mjsim.pyx
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/mjsimstate.pyx
   from /tmp/pip-uninstall-rdeaw6f9/mjsimstate.pyx
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/mjviewer.py
   from /tmp/pip-uninstall-rdeaw6f9/mjviewer.py
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/modder.py
   from /tmp/pip-uninstall-rdeaw6f9/modder.py
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/opengl_context.pyx
   from /tmp/pip-uninstall-rdeaw6f9/opengl_context.pyx
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/pxd/
   from /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/~xd
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/tests/
   from /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/~ests
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/utils.py
   from /tmp/pip-uninstall-rdeaw6f9/utils.py
  Moving to /home/user/anaconda3/envs/spinningup/lib/python3.6/site-packages/mujoco_py/version.py
   from /tmp/pip-uninstall-rdeaw6f9/version.py
ERROR: Command errored out with exit status 1: /home/user/anaconda3/envs/spinningup/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jvze_h7i/mujoco-py_35a193b81cbb4e02a16072099553e4b4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jvze_h7i/mujoco-py_35a193b81cbb4e02a16072099553e4b4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7uj0wk9y/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/anaconda3/envs/spinningup/include/python3.6m/mujoco-py Check the logs for full command output.
```

**Comment by YoungY620** [comment]
I got the same error.

**Comment by YoungY620** [comment]
The issue #295  is related to this one.
You do not have to install `gym[mujoco, robotics]` .

**Comment by HasarinduPerera** [comment]
Thanks a lot!
