### ISSUE TITLE
CalledProcessError while running experiment

### ISSUE THREAD

**Issue by hmishfaq** [openai/spinningup#362]
I am getting this error when trying to run
```
mpirun -np 12 python -m spinup.run ppo --hid "[32,32]" --env LunarLander-v2 --exp_name installtest --gamma 0.999
```

Why is this the case?

```
Traceback (most recent call last):
  File "/home/mila/i/ishfaqha/.conda/envs/spinningup/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mila/i/ishfaqha/.conda/envs/spinningup/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mila/i/ishfaqha/spinningup/spinup/run.py", line 248, in <module>
    parse_and_execute_grid_search(cmd, args)
  File "/home/mila/i/ishfaqha/spinningup/spinup/run.py", line 180, in parse_and_execute_grid_search
    eg.run(algo, **run_kwargs)
  File "/home/mila/i/ishfaqha/spinningup/spinup/utils/run_utils.py", line 546, in run
    data_dir=data_dir, datestamp=datestamp, **var)
  File "/home/mila/i/ishfaqha/spinningup/spinup/utils/run_utils.py", line 171, in call_experiment
    subprocess.check_call(cmd, env=os.environ)
  File "/home/mila/i/ishfaqha/.conda/envs/spinningup/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/mila/i/ishfaqha/.conda/envs/spinningup/bin/python', '/home/mila/i/ishfaqha/spinningup/spinup/utils/run_entrypoint.py', 'eJylU89rFDEUzuxs2+1urWKhxdJDwcsWcbcIXqRWYUEPU3qoHpWQTrIzcTLJdJK0VhCE2u4WgpdGL/5P3v0rPHr1zWxtFy8KTpiZl+/9yHtf3vvQ/PyqierHrcRCWVrwOBOsNyV7t4iHXAg8tDI2XEl/4bspcjdxTjKGdcYmKoABvYH3LReGS2yOCwaYaw0UZS+rzanf890I1SuMlgbPaDBuZLPlJm1QJNA57GhwB52jERoFwwYNafNjC7CZLVRpHiMTjMOTIEDj5hCQTyBR9AL57q5rMXmIJcmZj1A6//uQBhzSHgdv0BidBGC4e+pds8oaUtlwj/qpylk/54L0eZ/rdEgOUtLXBZeSy8QWtQg/a7jQ/dJKXEu94hiq2hIk36dk20dfB8inHRcmx7k/8xsGqnQPYwKMsbcFK3nOpOltCQWQ3u6Z1MoMF8Lqa+wqlput6hhKb3y65Fp5wfFQlVkVNr3l2te+PvoyWESNVlCt28Fs2ArBOTsiZaK9m5M2x3FhvZupXfwIEkyXznyVWxS+913XwbggcUYShrF3C5NKe3V9UByuuaw0y9Oa3hUHtQ10RW3zP0TaEaRUJTSXCLUPbMAmXf3j2IoHoxQo09ULr12LsiGxwmi/65qUxwac3CL0rLYlw4dEWKb9a9+t4s4kJM+Jf/7kx89v35dH9+CmFnesJOUOkZSV9w8feDdPYnzJHQRaSDmlTGLN303CROvROtOuqRmj0F/uhlBJwsprl65rK2sKazDlpXdP/8oHJQZUUhvoEsO0mZax3gR2oXUm/ew6UzpvbRS4tUtyiEhURaJRZZz2ikJVr3dh9b3wzM3miloY4HTDNetY6ZoLqYqBtRU8NeFY2/2JaVWu6xAplSHVqNd8tA4sEZNc7v5DW3vXzo6uL8iavd4vLc+kcg==']' returned non-zero exit status 15.
Running experiment:

installtest

with kwargs:

{
    "ac_kwargs":	{
        "hidden_sizes":	[
            32,
            32
        ]
    },
    "env_name":	"LunarLander-v2",
    "gamma":	0.999,
    "seed":	0
}





================================================================================


There appears to have been an error in your experiment.

Check the traceback above to see what actually went wrong. The 
traceback below, included for completeness (but probably not useful
for diagnosing the error), shows the stack leading up to the 
experiment launch.

================================================================================


```

**Comment by ShayekhBinIslam** [comment]
Hi @hmishfaq , I assume your goal is to run 12 experiments in parallel. There is an argument `--num_cpu` for the task. Directly, using `mpirun` is creating the issue, I guess. Following works for me:

`python -m spinup.run ppo --hid "[32,32]" --env LunarLander-v2 --exp_name installtest --gamma 0.999 --num_cpu 4`

![Figure_1](https://user-images.githubusercontent.com/38907457/160774711-046e4a8c-d4dc-4ffc-919f-7aa68e4eae72.png)

Ref: https://github.com/openai/spinningup/issues/68, https://github.com/openai/spinningup/issues/263.

**Comment by Jensen-Inequality** [comment]
I substitute `python -m spinup.run plot data/installtest/installtest_s0` with the following command
`python -m spinup.run plot data\\installtest\\installtest_s0`.
It works for me though I do not know where the problems lie.
