### ISSUE TITLE
not able to run command under the tag: After it finishes training, watch a video of the trained policy with  python -m spinup.run test_policy data/installtest/installtest_s0

### ISSUE THREAD

**Issue by Skizzy-create** [openai/spinningup#408]
![Screenshot 2024-02-21 101829](https://github.com/openai/spinningup/assets/112803348/e3d6487b-4ace-486e-a8e8-13973cddd4b9)
![Screenshot 2024-02-21 101912](https://github.com/openai/spinningup/assets/112803348/52673ae4-a281-4710-9931-7b0aabcea6a6)
The above screenshot presents the error I am facing while trying to see the video for the training.
the training went through, and I was able to see the training plot.  but not the video,

The specific error message is attached in the screenshots and the text below
```terminal
(spinningup) skizzy@R2D2:/mnt/d/RL-SpinningUp/spinningup$ python -m spinup.run test_policy data/installtest/installtest_s0


Loading from data/installtest/installtest_s0/pyt_save/model.pt.


/home/skizzy/conda/envs/spinningup/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Logging data to /tmp/experiments/1708490755/progress.txt
libGL error: MESA-LOADER: failed to open swrast: /home/skizzy/conda/envs/spinningup/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib/x86_64-linux-gnu/libLLVM-15.so.1) (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
Traceback (most recent call last):
  File "/mnt/d/RL-SpinningUp/spinningup/spinup/utils/test_policy.py", line 153, in <module>
    run_policy(env, get_action, args.len, args.episodes, not(args.norender))
  File "/mnt/d/RL-SpinningUp/spinningup/spinup/utils/test_policy.py", line 121, in run_policy
    env.render()
  File "/home/skizzy/conda/envs/spinningup/lib/python3.6/site-packages/gym/core.py", line 235, in render
    return self.env.render(mode, **kwargs)
  File "/home/skizzy/conda/envs/spinningup/lib/python3.6/site-packages/gym/envs/box2d/lunar_lander.py", line 320, in render
    from gym.envs.classic_control import rendering
  File "/home/skizzy/conda/envs/spinningup/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 27, in <module>
    from pyglet.gl import *
  File "/home/skizzy/conda/envs/spinningup/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 244, in <module>
    import pyglet.window
  File "/home/skizzy/conda/envs/spinningup/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1880, in <module>
    gl._create_shadow_window()
  File "/home/skizzy/conda/envs/spinningup/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 220, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/skizzy/conda/envs/spinningup/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 165, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/skizzy/conda/envs/spinningup/lib/python3.6/site-packages/pyglet/window/__init__.py", line 591, in __init__
    context = config.create_context(gl.current_context)
  File "/home/skizzy/conda/envs/spinningup/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 204, in create_context
    return XlibContextARB(self, share)
  File "/home/skizzy/conda/envs/spinningup/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 314, in __init__
    super(XlibContext13, self).__init__(config, share)
  File "/home/skizzy/conda/envs/spinningup/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 218, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context
Traceback (most recent call last):
  File "/home/skizzy/conda/envs/spinningup/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/skizzy/conda/envs/spinningup/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/d/RL-SpinningUp/spinningup/spinup/run.py", line 243, in <module>
    subprocess.check_call(args, env=os.environ)
  File "/home/skizzy/conda/envs/spinningup/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/skizzy/conda/envs/spinningup/bin/python', '/mnt/d/RL-SpinningUp/spinningup/spinup/utils/test_policy.py', 'data/installtest/installtest_s0']' returned non-zero exit status 1.


```

**Comment by Lisalsj** [comment]
I encountered the same issue as you. Have you resolved it?

**Comment by Skizzy-create** [comment]
I haven't been able to but it has to do something with openGL lib

**Comment by qihaoqian** [comment]
https://github.com/openai/spinningup/issues/377
