### ISSUE TITLE
No module named "tensorflow"

### ISSUE THREAD

**Issue by noobmaster29** [openai/spinningup#60]
I followed the installation process on this page (https://spinningup.openai.com/en/latest/user/installation.html). After I run pythonw -m spinup.run plot data/installtest/installtest_s0, I am getting the following error message. I'm working in a conda environment. 

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/anaconda3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/tf/Documents/reinforcement_learning/spinningup/spinup/__init__.py", line 2, in <module>
    from spinup.algos.ddpg.ddpg import ddpg
  File "/Users/tf/Documents/reinforcement_learning/spinningup/spinup/algos/ddpg/ddpg.py", line 2, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

Any idea why tensorflow is not available? I also tried a conda install and the same error. The other testing commands seem to run ok.

**Comment by noobmaster29** [comment]
I cannot run python -m spinup.run plot data/installtest/installtest_s0. 

It returns this error message: 

ImportError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.

**Comment by noobmaster29** [comment]
Yes, I have Tensorflow installed as well as Keras.

**Comment by HareshMiriyala** [comment]
maybe you are running python2.7 instead of python3.  Maybe your can make an alias for python3 using 
`alias python=python3`

and then run your script.

**Comment by tqa236** [comment]
I have the same problem, then I uninstall tensorflow by `pip uninstall tensorflow` and reinstall it using conda: `conda install tensorflow`, everything works fine.

 I think pip is not a good choice for installing packages inside virtual environment.

**Comment by nealmcb** [comment]
I also had the same problem. In my case, just re-running the pip install step fixed it. Things worked better after I upgraded pip from version 9 to version 19.
This is all in a Python 3 venv, which I prefer to conda.
