### ISSUE TITLE
Check your install issue 

### ISSUE THREAD

**Issue by m090009** [openai/spinningup#76]
Hi there,

after creating a conda environment, installing OpenMPI, and then cloning and installing Gym via `pip install -e .` I ran into trouble while running this experiment via: `python -m spinup.run ppo --hid "[32,32]" --env LunarLander-v2 --ecp_name installtest --gamma 0.999^C` to check the installation. 

Here is the error message:
`
Traceback (most recent call last):
  File "/home/USER/spinningup/spinup/utils/run_entrypoint.py", line 11, in <module>
    thunk()
  File "/home/USER/spinningup/spinup/utils/run_utils.py", line 162, in thunk_plus
    thunk(**kwargs)
TypeError: ppo() got an unexpected keyword argument 'ecp_name'
`

**Comment by m090009** [comment]
My bad, I miss-typed `exp-name`, sorry again Its late and I need to go to sleep.
