### ISSUE TITLE
not able to run PPO in the LunarLander-v2 env

### ISSUE THREAD

**Issue by jramak** [openai/spinningup#82]
I followed all the instructions here: https://spinningup.openai.com/en/latest/user/installation.html#check-your-install , but I have a problem with mpi4py. I tried the suggestion in stackoverflow (https://stackoverflow.com/questions/35370396/mpi4py-library-not-loaded-usr-local-lib-libmpi-1-dylib), but it does not work for me. Below is the error I'm seeing: 

Traceback (most recent call last):
  File "/Users/jramak1/miniconda3/envs/spinningup/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/jramak1/miniconda3/envs/spinningup/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/jramak1/dev/spinningup/spinup/__init__.py", line 2, in <module>
    from spinup.algos.ddpg.ddpg import ddpg
  File "/Users/jramak1/dev/spinningup/spinup/algos/ddpg/ddpg.py", line 7, in <module>
    from spinup.utils.logx import EpochLogger
  File "/Users/jramak1/dev/spinningup/spinup/utils/logx.py", line 14, in <module>
    from spinup.utils.mpi_tools import proc_id, mpi_statistics_scalar
  File "/Users/jramak1/dev/spinningup/spinup/utils/mpi_tools.py", line 1, in <module>
    from mpi4py import MPI
ImportError: dlopen(/Users/jramak1/miniconda3/envs/spinningup/lib/python3.6/site-packages/mpi4py/MPI.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libmpi.1.dylib
  Referenced from: /Users/jramak1/miniconda3/envs/spinningup/lib/python3.6/site-packages/mpi4py/MPI.cpython-36m-darwin.so
  Reason: image not found

**Comment by zhangbinxy** [comment]
Have you solved it ? I have the similar Error .

**Comment by jmichaux** [comment]
Maybe try running this on the command line first:

`module load mpi/openmpi-x86_64`

**Comment by jramak** [comment]
I have a macOS. I'm getting module command not found.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
If you are out of other options, could you try installing both pip and mpi4py through anaconda?
