### ISSUE TITLE
pip install -e . "python setup.py egg_info" failed

### ISSUE THREAD

**Issue by Hank-MIA** [openai/spinningup#84]
I'm using Ubuntu 18.04.1 LTS.
I'm at the last step of Installing Spinning Up. When execute `pip install -e .`   it tells me this:

> Obtaining file:///home/agent47/spinningup
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/home/agent47/spinningup/setup.py", line 7, in <module>
>         + "Please install it before proceeding."
>     AssertionError: The Spinning Up repo is designed to work with Python 3.6 and greater.Please install it before proceeding.
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /home/agent47/spinningup/
> 

I did all previous steps, and I checked my python version is 3.6.7. Why it tells me to install python first?

**Comment by Hank-MIA** [comment]
I used `pip3 install -e .` instead. It worked.
